### ISSUE TITLE
Introducing Terms and Conditions of Use, Privacy Policies and other Legal Issues

### ISSUE THREAD

**Issue by Daimon-Law** [pangolindex/pangolin.exchange#10]
The Pangolin team should consider introducing various terms and conditions, privacy policy and disclaimers across the site. I've been using Pangolin since it started and there are several areas that are worth exploring further:

1. **Terms and Conditions of Use.** This should incorporate exclusion provisions and indemnities designed to give developers some measure of protection if there is catastrophic failure or funds are lost. There should also be rights to exclude users/wallets who breach acceptable use terms, use the site for unlawful purposes etc...

2. **Privacy Policy**. What does Pangolin do with trading and account information that can be attributed to a user? How does it process, store, and distributed that data? Where is it stored? Who has access to it?

3. **Disclaimers** at the point of key trading and liquidity decisions. There aren't any warnings yet. That's not good practice.

4. **US-focused disclaimers and exclusions**. I strongly recommend the team consider whether Pangolin is going to be subject to US Securities and Exchanges laws and how to manage that risk. There are other jurisdictions that may not look kindly on Pangolin operations so it would be smart to think about mitigating that risk.

5. **Licensing, copyright terms**. Who owns the code? Who owns the site? Who is paying for hosting? On what conditions can it be used? If open-source, which open source terms are being used? They should be referenced on the site.

6. I didn't see any **age restrictions**. I know it's hard to manage this risk but the team should turn their mind to how they might be able to exclude minors. You can't have kids trading on Pangolin. That would be a public relations disaster and would definitely attract an official response.

Obviously I've only summarised the key issues to consider - there is quite a bit of complexity to each of these topics given the multi-jurisdictional questions raised. Some can be solved with legal drafting. Others require some coding. Some might not have an answer - this is bleeding edge legal territory.

**Comment by HariSeldon23** [comment]
This is a good topic to start raising. Some of these issues haven't been solved across any DEX that I'm aware of. 

With Pangolin being community owned, alot of these issues I'd assume would need to go to governance. Which will hopefully launch in a few months time. 

I'm personally very interested in point 5 that you made.

**Comment by HariSeldon23** [comment]
I'd like to re-engage this issue. We are currently redesigning the front end and would be good to include these within that redesign.
